package com.gem.pivot.wtk.generated_form;

import com.gem.pivot.wtk.ValidationError;

import java.util.List;

/**
 * <strong>Created with IntelliJ IDEA</strong><br/>
 * User: Jiri Pejsa<br/>
 * Date: 16.6.15<br/>
 * Time: 11:17<br/>
 * <p>To change this template use File | Settings | File Templates.</p>
 */
public interface AutoGeneratedFormPerformListener {

	void perform(final Object o);

	void validationError(final Object o, List<ValidationError> errors);

}
