package com.gem.pivot.wtk.generated_form;

import java.lang.reflect.Method;

/**
 * <strong>Created with IntelliJ IDEA</strong><br/>
 * User: Jiri Pejsa<br/>
 * Date: 18.6.15<br/>
 * Time: 9:23<br/>
 * <p>To change this template use File | Settings | File Templates.</p>
 */
public class AutoGeneratedFormComponent {
	protected AutoGeneratedForm autoGeneratedForm;

	public void propagateChangesToView() {
		if (autoGeneratedForm != null) {
			autoGeneratedForm.propagateModelToView();
		}
	}

	public void setProperty(final String propertyName, Object value) {
		try {
			findSetterMethod(propertyName).invoke(this, value);
			autoGeneratedForm.propertyChanged(propertyName, value);
		} catch (Exception e) {
			System.out.println("Can not propagate property change event on property " + propertyName + " with value " + value);
		}
	}

	private Method findSetterMethod(final String propertyName) throws NoSuchMethodException {
		final Method getter = this.getClass().getDeclaredMethod(getterName(propertyName));
		Class<?> clazz = getter.getReturnType();
		return this.getClass().getDeclaredMethod(setterName(propertyName), clazz);
	}

	private String setterName(final String fieldName) {
		if (fieldName != null && fieldName.length() >= 1) {
			return "set" + fieldName.substring(0, 1).toUpperCase() + fieldName.substring(1);
		} else {
			return null;
		}
	}

	private String getterName(final String fieldName) {
		if (fieldName != null && fieldName.length() >= 1) {
			return "get" + fieldName.substring(0, 1).toUpperCase() + fieldName.substring(1);
		} else {
			return null;
		}
	}


}
