package com.gem.pivot.wtk;

import com.gem.pivot.wtk.annotations.*;
import com.gem.pivot.wtk.generated_form.AutoGeneratedFormComponent;

import java.util.Calendar;
import java.util.List;

/**
 * <strong>Created with IntelliJ IDEA</strong><br/>
 * User: Jiri Pejsa<br/>
 * Date: 16.6.15<br/>
 * Time: 9:33<br/>
 * <p>To change this template use File | Settings | File Templates.</p>
 */
public class TestForm extends AutoGeneratedFormComponent {

	@Label("Křestní jméno")
	@Empty(false)
	private String firstName;

	@Nullable(true)
	@DatePicker(pattern = "dd/MM/yyyy", textInput = true)
	private Calendar dateCreated;

	@DatePicker(pattern = "dd.MM.yyyy", textInput = false)
	private Calendar datePicker;

	@ListView(dataProvider = MockListButtonDataProvider.class)
	@Label("Multiple Select")
	private List<User> roles;

	@ListView(dataProvider = MockListButtonDataProvider.class)
	@Label("Single Select")
	private User user;

	@Label("Hlavní role")
	@ListButton(dataProvider = MockListButtonDataProvider.class)
	@Nullable(false)
	private User mainRole;

	@Nullable(false)
	@Max(100)
	@Label("Částka")
	private Integer amount;


	public TestForm() {
	}

	public TestForm(String firstName) {
		this.firstName = firstName;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public Calendar getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(Calendar dateCreated) {
		this.dateCreated = dateCreated;
	}

	public List<User> getRoles() {
		return roles;
	}

	public void setRoles(List<User> roles) {
		this.roles = roles;
	}

	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public User getMainRole() {
		return mainRole;
	}

	public void setMainRole(User mainRole) {
		this.mainRole = mainRole;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Calendar getDatePicker() {
		return datePicker;
	}

	public void setDatePicker(Calendar datePicker) {
		this.datePicker = datePicker;
	}
}
